### Product Index

GET http://localhost:3000/products.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NTgyNTU4Mzh9.tvRRzOOswQmaBrXjwv1_x5TMny4R-jfVIFH_lgH-n1s

###Product Show

GET http://localhost:3000/product/34.json


### Product Create

POST http://localhost:3000/products.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NTgyNTU4Mzh9.tvRRzOOswQmaBrXjwv1_x5TMny4R-jfVIFH_lgH-n1s
Content-Type: application/json

{
  "name": "test name",
  "price": "test price",
  "image_url": "test image_url",
  "description": "test description"
}



### Product Update

PATCH http://localhost:3000/products/33.json
Content-Type: application/json

{

  "title": "Saber Tooth Tigers"
}

### Product Delete

DELETE http://localhost:3000/products/21.json

### Supplier Index

GET http://localhost:3000/supplier.json


### Supplier Show

GET http://localhost:3000/supplier/34.json

### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Casey Behrendt",
  "email": "test1@example.com",
  "password": "password12",
  "password_confirmation": "password12"
}

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "test1@example.com",
  "password": "password12"
}

### Sessions create
POST http://localhost:3000/sessions.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjozLCJleHAiOjE2NTc3MzU3OTl9.t3ut2yGnpKdrATMsI9Khg_oohjGF3F0Sx-NBQ7EPszY
Content-Type: application/json

{
  "name": "User name",
  "width": 640,
  "height": 480
}

### Order Create

POST http://localhost:3000/orders.json
Content-Type: application/json

{
  "user_id": 1,
  "product_id": 2,
  "quantity": 2,
  "subtotal": 9.99,
  "tax": 1.01,
  "subtotal": 11.00
}

### Order Show

GET http://localhost:3000/orders/1.json
### Product Index

GET http://localhost:3000/orders.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjozLCJleHAiOjE2NTc3MzU3OTl9.t3ut2yGnpKdrATMsI9Khg_oohjGF3F0Sx-NBQ7EPszY
Content-Type: application/json


### Carted_Products Create

POST http://localhost:3000/carted_products.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NTgyNTU4Mzh9.tvRRzOOswQmaBrXjwv1_x5TMny4R-jfVIFH_lgH-n1s
Content-Type: application/json

{
  "product_id": 1,
  "quantity": 3,
  "status": "carted"
  
}